# Generated by Django 2.1.7 on 2019-02-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BondRecommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='currency',
        ),
        migrations.AlterField(
            model_name='securities',
            name='G_spread',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='securities',
            name='OAS_spread',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='securities',
            name='modified_duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='securities',
            name='yld',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Rates',
        ),
    ]
