# Generated by Django 2.1.7 on 2019-03-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BondRecommender', '0002_auto_20190219_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='vanguard_merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bclass3', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=16)),
                ('bid_spread', models.FloatField()),
                ('cur_yld', models.FloatField()),
                ('g_spd', models.FloatField()),
                ('years_to_mat', models.FloatField()),
                ('OAS', models.FloatField()),
                ('OAD', models.FloatField()),
                ('amt_out', models.FloatField()),
                ('cpn', models.FloatField()),
                ('excess_rtn', models.FloatField()),
                ('ISIN', models.CharField(max_length=16)),
                ('ticker', models.CharField(max_length=16)),
                ('mty', models.CharField(max_length=16)),
                ('iss_dt', models.CharField(max_length=16)),
                ('px_close', models.FloatField()),
                ('KRD_6M', models.FloatField()),
                ('KRD_2Y', models.FloatField()),
                ('KRD_5Y', models.FloatField()),
                ('KRD_10Y', models.FloatField()),
                ('KRD_20Y', models.FloatField()),
                ('KRD_30Y', models.FloatField()),
                ('sp_rating_num', models.FloatField()),
                ('accrued_int', models.FloatField()),
                ('yield_to_mat', models.FloatField()),
                ('class_detail_code', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=16)),
            ],
        ),
    ]
